site_name: RL-Kernel
site_url: https://rl-align.github.io/RL-Kernel/
repo_url: https://github.com/RL-Align/RL-Kernel
edit_uri: edit/main/docs/
exclude_docs: |

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-2
        name: Switch to system preference
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - toc.follow

plugins:
  - meta
  - search
  - awesome-nav
  - git-revision-date-localized:
      exclude:
        - api/*

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - mkdocs/stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3.2.2/es5/tex-mml-chtml.js

strict: true
