# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 RL-Kernel Contributors

name: Auto-Request-Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Request Review from Core Team
        uses: actions/github-script@v7
        with:
          script: |
            const candidateReviewers = ['Flink-ddd', 'EthanZero2Hero', 'inaniloquentee', 'bitborne', 'maxiaosong1124', 'ziying'];

            const prAuthor = context.payload.pull_request.user.login;

            const finalReviewers = candidateReviewers.filter(user => user !== prAuthor);

            if (finalReviewers.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: finalReviewers
              });
              console.log(`Successfully requested review from: ${finalReviewers.join(', ')}`);
            } else {
              console.log("PR author is the only reviewer. Skipping request.");
            }
